-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfSJZy05eyTuGfj7r
chDJl7B10qxIt70HKjYnU+I9LzWgCgYIKoZIzj0DAQehRANCAARaVFRimppC/dSI
roVHTNXst38bq/Adk/zkShZ2VZ0XWjnLUApic8WzIm2cYh+kZS4cd9kOSu3FIPh/
Mep88SOH
-----END PRIVATE KEY-----